final int PRIMARY_COLOR = 0xFF4B39EF;
final int ALTERNATE_COLOR = 0xFFFF5963;
final int SECONDARY_COLOR = 0xFF39D2C0;
final String CPF_HOUSING_GRANT = 'CPF_HOUSING_GRANT';
final int CPF_HOUSING_GRANT_AMOUNT = 80000;
final String CPF_HOUSING_GRANT_5RM = 'CPF_HOUSING_GRANT_5RM';
final int CPF_HOUSING_GRANT_AMOUNT_5RM = 50000;

final String CPF_HOUSING_GRANT_FAMILY = 'CPF_HOUSING_GRANT_FAMILY';
final int CPF_HOUSING_GRANT_AMOUNT_FAMILY = 40000;

final String CPF_HOUSING_GRANT_FAMILY_5RM = 'CPF_HOUSING_GRANT_FAMILY_5RM';
final int CPF_HOUSING_GRANT_AMOUNT_FAMILY_5RM = 30000;

final String HALF_HOUSING_GRANT = 'HALF_HOUSING_GRANT';
final String ENHANCED_CPF_HOUSING = 'ENHANCED_CPF_HOUSING';
final int ENHANCED_CPF_HOUSING_AMOUNT = 5000;

final String SINGLE_GRANT = 'SINGLE_GRANT';
final int SINGLE_GRANT_AMOUNT = 400000;

final String SINGLE_GRANT_5RM = 'SINGLE_GRANT_5RM';
final int SINGLE_GRANT_5RM_AMOUNT = 25000;

final String PROXIMITY_GRANT = 'PROXIMITY_GRANT';
